### ISSUE TITLE
How to uninstall this nepali romanized pro?

### ISSUE THREAD

**Issue by davidwebb444** [suvash/nepali-romanized-pro#10]
This is a super useful thing that u created. I once installed this Romanized pro. How can I uninstall it? Any suggestion suvash? Thanks in advance.

**Comment by suvash** [comment]
Could you provide some more context as to why you need to do this ? You can simply remove it from your prefered keyboards. If you want to force remove the layout you can remove the related files from `/Library/Keyboard Layouts`, two of them.
