### ISSUE TITLE
Compatibility with OSX Mavericks

### ISSUE THREAD

**Issue by sangharsha** [suvash/nepali-romanized-pro#4]
It was working great until I upgraded to Mavericks. I'm sure the OS wiped out this package. I reinstalled the app, restarted the machine and in the input sources I cannot find Nepali Romanized Pro.

It would be great to have it in the Mavericks as well.

**Comment by sangharsha** [comment]
Hi there. Has there been any changes in the OSX lately? because when I type in Romanized Nepali, the "ai" sound becomes distorted. For instance, typing "kasaiko" becomes "कस ैको". Any idea about this issue?

**Comment by suvash** [comment]
Hi there, I haven't yet used it on Yosemite, but will soon. Can you open another issue with some more details on the OS you are using and the problem you are having ? I'll try and look at it asap.

**Comment by sangharsha** [comment]
Sure. I just did.
