### ISSUE TITLE
Compatibility with OSX Yosemite

### ISSUE THREAD

**Issue by sangharsha** [suvash/nepali-romanized-pro#8]
The tool doesn't work as expected in OSX Yosemite (10.10.3). When we type in Romanized Nepali, the "ai" sound becomes distorted. For instance, typing "kasaiko" becomes "कस ैको". It should have resulted in "कसैको". Haven't noticed any other major issue except this one. 

Examples: म ैले, कस ैको, जस्त ै, घर ैमा।

**Comment by suvash** [comment]
Okies, let me give this a go.

**Comment by suvash** [comment]
I don't seem to have this issue. (on 10.10.4 here though) Works on all input fields in most of the application. Is this some application specific issue or on the whole OS ?

ksEko -> कसैको

**Comment by sangharsha** [comment]
The issue is prevalent in all Apps throughout the OS.

For instance, nepalai ma jastai (nepalEma jstE) becomes: नेपाल ैमा जस्त ै

Do you think uninstalling and installing it again would help?

**Comment by suvash** [comment]
That is indeed very odd, try reinstalling and also upgrading osx to the latest version.
( If you want to force remove the layout you can remove the related files from `/Library/Keyboard Layouts`, two of them. However, this should be unnecessary. ) Let me know if that works.

**Comment by suvash** [comment]
@sangharsha Did this work for you ?

**Comment by davidwebb444** [comment]
once installed this Romanized pro. How can I uninstall it? Any suggestion suvash?
