### ISSUE TITLE
The R (ृ) has extra space

### ISSUE THREAD

**Issue by chadhlmr** [suvash/nepali-romanized-pro#9]
R (ृ) has extra space before it, resulting in क ृ instead of कृ.

**Comment by suvash** [comment]
noted, will be fixing it in the next release.

**Comment by mxxvi** [comment]
looks like I arrived here late to report the same issue.
has there been any update yet?

**Comment by suvash** [comment]
oh. I completely forgot about this. will dig into this repo again and make a new release sometime this month. thanks.

**Comment by rajushrestha** [comment]
@suvash I believe this issue came from here: [packager/Nepali Romanized Pro.keylayout#L164](https://github.com/suvash/nepali-romanized-pro/blob/master/packager/Nepali%20Romanized%20Pro.keylayout#L164). I see extra whitespace before  ृ symbol. It will be nice if you solve this.

**Comment by rajushrestha** [comment]
If anyone want to solve issue without waiting for new release, you can do that manually.
Open this file on your text editor of choice:
`/Library/Keyboard\ Layouts/Nepali\ Romanized\ Pro.keylayout`

Go to line no: 164 and replace with this --> `<key code="15" output="ृ"/>`
Go to line no: 304 and replace with this --> `<key code="44" output="्"/>` - This is issue I found and described in comment above.

And log out from your currently logged in user. Now this issue will be solved and you can write Krishna in proper way.
Before: क ृ ष्ण
After: कृष्ण

**Comment by suvash** [comment]
Thanks @rajushrestha ! Yes, the solution you've mentioned should work. The fix is simple, but I have to dig in latest macOS packaging + signing things that might have changed quite a bit.
Curious what version of macOS (or OS X) you're running on ?

**Comment by rajushrestha** [comment]
You are welcome @suvash, I'm using Mojave 10.14.6 (not latest os). 
If it is working on older and latest versions now, it should work fine as it is now.

**Comment by suvash** [comment]
good to know. I'll make some time to dig into this new format of packaging and see how feasible it is.

**Comment by mxxvi** [comment]
Thanks guys... it was a life saver
I am currently on Catalina 10.15.4 and @rajushrestha 's fix works perfectly

**Comment by suvash** [comment]
@chadhlmr @mxxvi @rajushrestha I've just pushed out a new package with the fix, updated the readme. will close this issue now.
